//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Entites
{
    using Abp.Domain.Entities;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OT_ClauseDataItem : Entity
    {
        [Key]
        public Guid ObjectID { get; set; }
        public string ParentObjectID { get; set; }
        public string WorkflowPackage { get; set; }
        public string WorkflowName { get; set; }
        public string ColumnName { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> ColumnLength { get; set; }
        public string LogicType { get; set; }
        public string Description { get; set; }
    }
}
