//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace  OA.Entites
{
    using Abp.Domain.Entities;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OT_WorkItem : Entity
    {
        [Key]
        public Guid ObjectID { get; set; }
        public string InstanceId { get; set; }
        public string TokenId { get; set; }
        public string WorkflowPackage { get; set; }
        public string WorkflowName { get; set; }
        public Nullable<int> WorkflowVersion { get; set; }
        public string Participant { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<bool> Approval { get; set; }
        public string ItemComment { get; set; }
        public string ColumnName { get; set; }
        public Nullable<int> ParticipantType { get; set; }
        public string GraphicalID { get; set; }
        public string ParticipantText { get; set; }

        public virtual OT_InstanceContext OT_InstanceContext { get; set; }
    }
}
