//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Entites
{
    using Abp.Domain.Entities;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Q_Department : Entity
    {
        public Q_Department()
        {
            this.Q_Role = new HashSet<Q_Role>();
            this.Q_UserInfo = new HashSet<Q_UserInfo>();
        }

        [Key]
        public int depId { get; set; }
        public Nullable<int> depPid { get; set; }
        public string depName { get; set; }
        public string depRemark { get; set; }
        public Nullable<bool> depIsDel { get; set; }
        public Nullable<System.DateTime> depAddTime { get; set; }

        public virtual ICollection<Q_Role> Q_Role { get; set; }
        public virtual ICollection<Q_UserInfo> Q_UserInfo { get; set; }
    }
}
