//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Entites
{
    using Abp.Domain.Entities;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Q_UserInfo : Entity
    {
        public Q_UserInfo()
        {
            this.Q_UserRole = new HashSet<Q_UserRole>();
          
        }
        [Key]
        public int uId { get; set; }
        public Nullable<int> uDepId { get; set; }
        public string uLoginName { get; set; }
        public string uName { get; set; }
        public string uEmail { get; set; }
        public string uPwd { get; set; }
        public Nullable<bool> uGender { get; set; }
        public string uPost { get; set; }
        public string uRemark { get; set; }
        public string uAddress { get; set; }
        public Nullable<bool> uIsDel { get; set; }
        public Nullable<System.DateTime> uAddTime { get; set; }

        public virtual Q_Department Q_Department { get; set; }
        public virtual ICollection<Q_UserRole> Q_UserRole { get; set; }
       
    }
}
