//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Entites
{
    using Abp.Domain.Entities;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Q_UserRole: Entity
    {
        [Key]
        public int urId { get; set; }
        public Nullable<int> urUId { get; set; }
        public Nullable<int> urRId { get; set; }
        public Nullable<bool> urIsDel { get; set; }
        public Nullable<System.DateTime> urAddtime { get; set; }
    
        public virtual Q_Role Q_Role { get; set; }
        public virtual Q_UserInfo Q_UserInfo { get; set; }
    }
}
